# Generated by Django 5.1.4 on 2025-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubstafftask',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hubstafftask',
            name='start_time',
            field=models.DateField(),
        ),
    ]
