# Generated by Django 5.1.4 on 2025-01-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hubstafftask_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubstafftask',
            name='is_active',
        ),
    ]
