# Generated by Django 5.1.4 on 2025-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_hubstafftask_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubstafftask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
